language: c++
sudo: required
services:
    - docker

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python3-dev python python3-pip chrpath

install:
    - pip3 install -r app/requirements.txt

script:
    # Compile app
    - nuitka --portable --show-progress --show-scons --remove-output --improved --python-flag=no_site app/app.py

    # Copy dependent linked libs
    # See the ldd_cp.sh script for an explanation of what/what this does
    - chmod +x build_scripts/ldd_cp.sh
    - build_scripts/ldd_cp.sh "app.dist/app.exe" "app.dist"

    # What did we end up with??
    - ls -lhR app.dist

    # Docker Build
    # travis makes this somewhat complicated
    # docker build app.dist -t blah does not work because app.dist is actually a symlink
    # so lets actually get in there!
    - cp Dockerfile app.dist
    - cd app.dist
    - docker build -t $REPO:$COMMIT .

    # Test it!
    # Run container
    - CONTAINER=`docker run -d -p 8001:8001 $REPO:$COMMIT`
    - echo $CONTAINER

    # Try and curl it
    - sleep 30
    - curl http://localhost:8001/

after_success:
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
    - curl -X POST https://hooks.microbadger.com/images/transactcharlie/nuitka-docker-example/YY_gyMFSYOxt85AvTrde9_W8vu8=

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=transactcharlie/nuitka-docker-example

  - secure: "eDTEraatWBwp9vyfae5PPkmAiJ8OfqtLCg++HZNFQKYpfHqK9gx25kizAaFn1Ers+CXn0SoVm7SH3dknLC2MS/zBX3nBHJsXFEPYwb8ivPMYk+0BU1HyNnPsz9OdOgan5psjV4sEv1xpvy80Jy9x4y3xgpdZh+j1fHnwdnCrOafKFaqj/MwYPinuNCvMn4SQK3BKXxCILT5iyC3/tkXDZfLSQV91zQzc9c1mQbpipqU336invl43jqEIWFVX1ztMvY2x5DWWn7Mj2kBratexyC/XfcVsgTVUbI/RYYf150aQVv7uPIDT6OMEcoq5uG1S2OovpjirNsmCop91OY1+kYeewUK3gwCe0sXOTCM4evfMjAC6KpvCiooLuLgfc4ojCpKCirpjNJU/5QzFqdhNNLJTLDkdHZgvQvcDO9ideewvjxZCqgDXpK9GOQ5DAdsm5wEBXaVawgega8so2RDBWRqwTzzYNpSO2QTOiQJWigVzUtYJrAMWhutHEW+o8nLy8aVV7QIQIxjxDQ5LNNvtRUI015oW1IcQieUEsxxTcUalTtT1xA/q+lbapdj4cagU3Fu8al6kyiRBb971SrJwwTO+jF5CF4TDkdXA8/5z8RLCPqEUbCjBhoTstDieGjeph3nJ/uVvGFaSuxxZyOxiG9rlzHRHp86oh+rBqp/S6bc="

  - secure: "o2xG1789etwmymUgO1/D1lR5rL1svIFw4URO5O0rk+BEyToMaYg4R76ZS4htx0b17n+9Eyr/sQE2nLnORgHL4BptwmSsjT5mcJlMITmMQwIyLIemgKXv1JMZBL7v99VmncTQpnBbbdzGOmrr50d6ZsGw1gElH7n51jkyX776o219guTeddoZ996c9/oYEiSPvYZh3hwAsxt76ZnGvpmT4f92au/PWMVnsvoJEfb2ERNCqemrOsrUf9Zk+v2gxAohVgvn1k5bOMfw6kuzT5lxDgwnLTku2kZg6L2hE/C4TBtAyaoidHM/L0MWNHXPDycQ5zidfsvgq5PlBaQtsD98fb7YhnRWKs6Ft7iVITnIodWgRl493uSRqYz0UFV6RHHwYkQ7X+Dqsad+rfkPIq7z8kcvOUTFfiEPJb0svx6IpnJp7NT+AeK0yPczJIHUs6o3n/0E7OJKX9RBwmsK0xr44o0gQ66t4UiHBkflLImHwO/Ejc0DoozpGdqyq4xymJjtjO0BViJPaygcoaUvPRRj7u5HUym86dvZbg1zobnxDv51FrhiGR7+YHt1iKoOmm33ZRuDNz5ILpd9nnydddZJnw6KxP1WmISXnFb4WhaFDRSEXWK7hQeyb2dqHl0ygHZUXiIltzirIR/T9i916TCXkcPdqmzFBAz+t32gqwzQzjw="
