#!/bin/bash

# This hook gets executed by the dockerhub build service
# $IMAGE_NAME is injected by dockerhub for us to tag our images with

docker build \
	--build-arg VCS_REF=`git rev-parse --short HEAD` \
	--build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
	-t "${IMAGE_NAME}" \
	.
